# -*- encoding: utf-8 -*-
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'version'

Gem::Specification.new do |gem|
  gem.name          = "optimus-ep"
  gem.version       = Optimus::VERSION
  gem.authors       = ["Nate Vack"]
  gem.email         = ["njvack@wisc.edu"]
  gem.description   = %q{Utilities to process behavioral data generated by E-Prime}
  gem.summary       = %q{Utilities to process behavioral data generated by E-Prime}
  gem.homepage      = "http://github.com/njvack/optimus-ep"

  gem.files         = `git ls-files`.split($/)
  gem.executables   = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.require_paths = ["lib"]
  
  gem.add_runtime_dependency "rparsec-ruby19", ">=1.0"
  gem.add_development_dependency "rspec"
  
end
