require 'echoe'
require './lib/version'

Echoe.new("optimus-ep", Optimus::VERSION::STRING) do |p|
  p.author = "Nate Vack"
  p.email = "njvack@wisc.edu"
  p.summary = "Utilities to process behavioral data generated by E-Prime"
  p.url = "http://github.com/njvack/optimus-ep"
  p.runtime_dependencies = ["rparsec-ruby19 >=1.0"]
  p.development_dependencies = ["rspec"]
end
